openapi: '3.0.1'
info:
  title: Microblog
  description: Aplicação de microblogging.
    Um microblog é uma aplicação em que os autores escrevem textos curtos (geralmente limitados a 144 caracteres), chamados de publicações.
    Geralmente publicações podem conter fotos ou vídeos e os usuários podem curtir e comentar publicações.
    Nesta versão, não há cadastro de usuários nem suporte a fotos, vídeos, curtidas ou comentários.
  version: '1.1'
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: '8000'

paths:
  /publicacoes:
    get:
      operationId: getPublicacoes
      summary: Acessar publicações
      responses:
        '200':
          description: 'OK'
          content: 
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/publicacao'
    
    post:
      summary: Criar publicação
      operationId: postPublicacao
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                autor:
                  $ref: '#/components/schemas/publicacao/properties/autor'
                texto:
                  $ref: '#/components/schemas/publicacao/properties/texto'
      responses:
        201:
          description: Publicação criada

  /publicacoes/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/publicacao/properties/id"
  
    get:
      operationId: getPublicacao
      summary: Acessar publicação
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#components/schemas/publicacao'
        404:
          description: 'Publicação não encontrada.'

    put:
      summary: Alterar publicação
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                autor:
                  $ref: '#/components/schemas/publicacao/properties/autor'
                texto:
                  $ref: '#/components/schemas/publicacao/properties/texto'
      responses:
        200:
          description: 'OK'
        404:
          description: 'Publicação não encontrada.'

    delete:
      summary: Apagar publicação
      responses:
        200:
          description: 'OK'
        404:
          description: 'Publicação não encontrada.'


components:
  schemas:  
    publicacao:
      type: object
      description: Uma publicação.
      properties:
        id:
          type: string
          description: Um id gerado automaticamente pelo sistema.
          example: 123
        autor:
          type: string
          description: O nome de usuário do autor.
          example: ciromdrs
        texto:
          type: string
          maxLength: 144
        criacao:
          type: string
          format: date-time

    msg:
      type: object
      properties:
        tipo:
          type: string
          enum: [info, erro]
        conteudo:
          type: string
