BEGIN TRANSACTION;
DROP TABLE IF EXISTS "baldes";
CREATE TABLE IF NOT EXISTS "baldes" (
	"id"	INTEGER NOT NULL,
	"nome"	TEXT NOT NULL UNIQUE,
	"usuario"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "objetos";
CREATE TABLE IF NOT EXISTS "objetos" (
	"id"	INTEGER NOT NULL,
	"chave"	TEXT NOT NULL UNIQUE,
	"valor"	TEXT NOT NULL,
	"usuario"	TEXT NOT NULL,
	"balde"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
